CREATE TABLE vacant_jobs (
    job_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR2(200)  NOT NULL,
    description  VARCHAR2(4000) NOT NULL,
    posted_by    VARCHAR2(100)  DEFAULT USER NOT NULL,
    is_active    CHAR(1)        DEFAULT 'Y' NOT NULL,
    expires_at   TIMESTAMP      NOT NULL,
    created_at   TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT ck_vj_active  CHECK (is_active IN ('Y','N')),
    CONSTRAINT ck_vj_expiry  CHECK (expires_at > created_at)
);

CREATE TABLE notification (
    notification_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id          NUMBER,
    notif_type      VARCHAR2(30)   NOT NULL,
    subject         VARCHAR2(400)  NOT NULL,
    body            VARCHAR2(4000) NOT NULL,
    status          VARCHAR2(10)   DEFAULT 'PENDING' NOT NULL,
    created_at      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    sent_at         TIMESTAMP,
    CONSTRAINT fk_notif_job  FOREIGN KEY (job_id)
        REFERENCES vacant_jobs(job_id) ON DELETE SET NULL,
    CONSTRAINT ck_notif_type CHECK (notif_type IN ('NEW_POSTING','DAILY_DIGEST')),
    CONSTRAINT ck_notif_stat CHECK (status IN ('PENDING','SENT','FAILED')),
    CONSTRAINT ck_notif_sent CHECK ((status = 'SENT' AND sent_at IS NOT NULL)
                                 OR (status != 'SENT'))
);

CREATE TABLE job_applications (
    application_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id          NUMBER        NOT NULL,
    applicant_name  VARCHAR2(150) NOT NULL,
    applicant_email VARCHAR2(150) NOT NULL,
    applied_at      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_app_job FOREIGN KEY (job_id)
        REFERENCES vacant_jobs(job_id) ON DELETE CASCADE,
    CONSTRAINT uq_app_once UNIQUE (job_id, applicant_email)
);

CREATE TABLE jobs_posting_archive (
                job_id       NUMBER         PRIMARY KEY,
                title        VARCHAR2(200)  NOT NULL,
                description  VARCHAR2(4000) NOT NULL,
                posted_by    VARCHAR2(100)  NOT NULL,
                expires_at   TIMESTAMP      NOT NULL,
                created_at   TIMESTAMP      NOT NULL,
                archived_at  TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL
);


--(1) Long-lived, already lower case.
--     The control row. Must survive every clock job untouched.
INSERT INTO vacant_jobs (job_id, title, description, posted_by, expires_at)
VALUES (101, 'Backend Engineer',
        'we are hiring a backend engineer with strong oracle plsql experience.',
        'hr.amal', SYSTIMESTAMP + INTERVAL '30' DAY);
 
-- (2) Long-lived, TYPED IN SHOUTING CAPITALS.
--     Proves step 05/06: the BEFORE UPDATE trigger + your own function.
--     Seeded loud on purpose -- it is also the row the step 10 sweep
--     must catch if the insert path ever misses it.
INSERT INTO vacant_jobs (job_id, title, description, posted_by, expires_at)
VALUES (102, 'Data Analyst',
        'URGENT VACANCY. WE NEED A DATA ANALYST TO JOIN THE TEAM IMMEDIATELY.',
        'hr.amal', SYSTIMESTAMP + INTERVAL '30' DAY);
 
-- (3) Mixed case with punctuation and digits.
--     Proves the function only touches A-Z and leaves the rest alone.
INSERT INTO vacant_jobs (job_id, title, description, posted_by, expires_at)
VALUES (103, 'DevOps Engineer',
        'DevOps role -- Kubernetes, CI/CD, 5+ years. Salary: 1,200 OMR/month!',
        'hr.saif', SYSTIMESTAMP + INTERVAL '30' DAY);
 
-- (4) Expires in TWO MINUTES.
--     The whole point of the seed. Without this you cannot watch lane C
--     work inside a coffee break. Step 07 flips it, 08 archives it,
--     09 purges it -- all while you sit and watch.
INSERT INTO vacant_jobs (job_id, title, description, posted_by, expires_at)
VALUES (104, 'Temporary QA Tester',
        'SHORT CONTRACT QA ROLE, CLOSING VERY SOON.',
        'hr.saif', SYSTIMESTAMP + INTERVAL '2' MINUTE);
 
-- (5) Expires in FIVE MINUTES.
--     A second row on a different clock, so you can prove the expiry
--     job is selective -- it must flip 104 and NOT this one on the
--     first tick.
INSERT INTO vacant_jobs (job_id, title, description, posted_by, expires_at)
VALUES (105, 'Office Administrator',
        'administrative support role for the muscat office.',
        'hr.saif', SYSTIMESTAMP + INTERVAL '5' MINUTE);
 
-- (6) Already inactive, never expired.
--     Proves step 08/09 key off is_active and not off expires_at.
--     A row can be taken down manually; the archive must still catch it.
INSERT INTO vacant_jobs (job_id, title, description, posted_by, is_active, expires_at)
VALUES (106, 'Withdrawn Role',
        'this posting was pulled by hr before it expired.',
        'hr.amal', 'N', SYSTIMESTAMP + INTERVAL '30' DAY);
 
COMMIT;

INSERT INTO job_applications (job_id, applicant_name, applicant_email)
VALUES (101, 'Fatma Al-Harthy', 'fatma.h@example.om');
INSERT INTO job_applications (job_id, applicant_name, applicant_email)
VALUES (101, 'Yusuf Rahman',    'yusuf.r@example.om');
INSERT INTO job_applications (job_id, applicant_name, applicant_email)
VALUES (101, 'Priya Nair',      'priya.n@example.om');
 
-- Posting 102: exactly ONE. Proves the digest counts, not just detects.
INSERT INTO job_applications (job_id, applicant_name, applicant_email)
VALUES (102, 'Omar Al-Balushi', 'omar.b@example.om');
 
INSERT INTO job_applications (job_id, applicant_name, applicant_email)
VALUES (104, 'Layla Said', 'layla.s@example.om');
 
COMMIT;

-- a function that convert to lower case
CREATE OR REPLACE FUNCTION my_lower (p_text IN VARCHAR2)
    RETURN VARCHAR2
    DETERMINISTIC
IS
    v_result VARCHAR2(4000) := NULL;
    v_char   VARCHAR2(1);
    v_code   PLS_INTEGER;
BEGIN
    -- Guard. In Oracle an empty string IS NULL, so this covers both.
    -- Without it, LENGTH(NULL) is NULL, the loop never runs, and you
    -- silently return NULL anyway -- but being explicit documents intent.
    IF p_text IS NULL THEN
        RETURN NULL;
    END IF;
 
    FOR i IN 1 .. LENGTH(p_text) LOOP
        v_char := SUBSTR(p_text, i, 1);
        v_code := ASCII(v_char);
 
        IF v_code BETWEEN 65 AND 90 THEN      -- 'A' .. 'Z'
            v_result := v_result || CHR(v_code + 32);
        ELSE
            v_result := v_result || v_char;   -- digits, spaces, Arabic, punctuation
        END IF;
    END LOOP;
 
    RETURN v_result;
END my_lower;
/

SELECT job_id, my_lower(description) AS normalised
  FROM vacant_jobs
 WHERE ROWNUM <= 3;
 
 
 CREATE OR REPLACE PROCEDURE register_notification (
    p_job_id  IN NUMBER,
    p_type    IN VARCHAR2,
    p_subject IN VARCHAR2,
    p_body    IN VARCHAR2
)
IS
BEGIN
    INSERT INTO notification (job_id, notif_type, subject, body, status)
    VALUES (p_job_id, p_type, p_subject, p_body, 'PENDING');
END register_notification;
/

--Trigger for a new posting
CREATE OR REPLACE TRIGGER trg_vj_new_posting
AFTER INSERT ON vacant_jobs
FOR EACH ROW
BEGIN
    register_notification(
        :NEW.job_id,
        'NEW_POSTING',
        'New vacancy: ' || :NEW.title,
        'A new job has been posted: ' || :NEW.description
    );
END;
/

--Trigger for a description edit
CREATE OR REPLACE TRIGGER trg_vj_lowercase
BEFORE INSERT OR UPDATE OF description ON vacant_jobs
FOR EACH ROW
BEGIN
    :NEW.description := my_lower(:NEW.description);
END;
/

--Expiry
CREATE OR REPLACE PROCEDURE expire_postings
IS
BEGIN
    UPDATE vacant_jobs
       SET is_active = 'N'
     WHERE is_active = 'Y'
       AND expires_at < SYSTIMESTAMP;
    COMMIT;
END expire_postings;
/


CREATE OR REPLACE PROCEDURE ensure_archive_table
IS
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
      FROM user_tables WHERE table_name = 'JOBS_POSTING_ARCHIVE';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE jobs_posting_archive (
                job_id      NUMBER PRIMARY KEY,
                title       VARCHAR2(200)  NOT NULL,
                description VARCHAR2(4000) NOT NULL,
                posted_by   VARCHAR2(100)  NOT NULL,
                expires_at  TIMESTAMP      NOT NULL,
                created_at  TIMESTAMP      NOT NULL,
                archived_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
            )]';
    END IF;
END ensure_archive_table;
/
--Archive + purge together
CREATE OR REPLACE PROCEDURE archive_and_purge
IS
BEGIN
    ensure_archive_table;

    INSERT INTO jobs_posting_archive
        (job_id, title, description, posted_by, expires_at, created_at)
    SELECT job_id, title, description, posted_by, expires_at, created_at
      FROM vacant_jobs
     WHERE is_active = 'N';

    DELETE FROM vacant_jobs WHERE is_active = 'N';

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END archive_and_purge;
/

CREATE OR REPLACE PROCEDURE sweep_descriptions
IS
BEGIN
    FOR r IN (SELECT job_id, description
                FROM vacant_jobs
               WHERE is_active = 'Y'
                 AND description != my_lower(description))
    LOOP
        UPDATE vacant_jobs
           SET description = my_lower(r.description)
         WHERE job_id = r.job_id;
    END LOOP;
    COMMIT;
END sweep_descriptions;
/

--count how many applicant applied for a job
CREATE OR REPLACE PROCEDURE daily_digest
IS
BEGIN
    FOR r IN (SELECT j.job_id,
                     j.description,
                     COUNT(a.application_id) AS applicant_count
                FROM vacant_jobs j
                LEFT JOIN job_applications a ON a.job_id = j.job_id
               WHERE j.is_active = 'Y'
               GROUP BY j.job_id, j.description)
    LOOP
    DECLARE
                v_exists NUMBER;
            BEGIN
                SELECT COUNT(*) INTO v_exists
                  FROM notification
                 WHERE job_id = r.job_id
                   AND notif_type = 'DAILY_DIGEST'
                   AND TRUNC(created_at) = TRUNC(SYSDATE);
        IF v_exists = 0 THEN
            register_notification(
                r.job_id,
                'DAILY_DIGEST',
                'Daily digest for job ' || r.job_id,
                'Job ' || r.job_id || ' — ' || r.description ||
                ' — applicants: ' || r.applicant_count
        );
        END IF;
        END;
    END LOOP;
    COMMIT;
END daily_digest;
/
SHOW ERRORS

EXEC daily_digest;

SELECT job_id, body FROM notification
 WHERE notif_type = 'DAILY_DIGEST';



BEGIN
    FOR j IN (SELECT job_name FROM user_scheduler_jobs
               WHERE job_name IN ('JOB_EXPIRE_POSTINGS','JOB_ARCHIVE_PURGE',
                                  'JOB_SWEEP_DESCRIPTIONS','JOB_DAILY_DIGEST'))
    LOOP
        DBMS_SCHEDULER.DROP_JOB(j.job_name, force => TRUE);
    END LOOP;
END;
/

BEGIN
    DBMS_SCHEDULER.CREATE_JOB(
        job_name        => 'JOB_EXPIRE_POSTINGS',
        job_type        => 'STORED_PROCEDURE',
        job_action      => 'EXPIRE_POSTINGS',
        start_date      => SYSTIMESTAMP,
        repeat_interval => 'FREQ=MINUTELY; INTERVAL=1',
        enabled         => TRUE,
        comments        => 'flip expired postings inactive');
END;
/
--creating the jobs
BEGIN
    DBMS_SCHEDULER.CREATE_JOB(
        job_name        => 'JOB_ARCHIVE_PURGE',
        job_type        => 'STORED_PROCEDURE',
        job_action      => 'ARCHIVE_AND_PURGE',
        start_date      => SYSTIMESTAMP,
        repeat_interval => 'FREQ=MINUTELY; INTERVAL=1',
        enabled         => TRUE,
        comments        => 'archive then purge, one transaction');

    DBMS_SCHEDULER.CREATE_JOB(
        job_name        => 'JOB_SWEEP_DESCRIPTIONS',
        job_type        => 'STORED_PROCEDURE',
        job_action      => 'SWEEP_DESCRIPTIONS',
        start_date      => SYSTIMESTAMP,
        repeat_interval => 'FREQ=MINUTELY; INTERVAL=5',
        enabled         => TRUE,
        comments        => 'lower-case sweep of the whole board');

    DBMS_SCHEDULER.CREATE_JOB(
        job_name        => 'JOB_DAILY_DIGEST',
        job_type        => 'STORED_PROCEDURE',
        job_action      => 'DAILY_DIGEST',
        start_date      => SYSTIMESTAMP,
        repeat_interval => 'FREQ=DAILY; INTERVAL=1',
        enabled         => TRUE,
        comments        => 'one digest per posting per day');
END;
/

BEGIN
    FOR j IN (SELECT job_name FROM user_scheduler_jobs
               WHERE job_name IN ('JOB_EXPIRE_POSTINGS','JOB_ARCHIVE_PURGE',
                                  'JOB_SWEEP_DESCRIPTIONS','JOB_DAILY_DIGEST'))
    LOOP
        DBMS_SCHEDULER.DROP_JOB(j.job_name, force => TRUE);
    END LOOP;
END;
/

-- the four jobs and their clocks
SELECT job_name, enabled, repeat_interval, state, next_run_date
  FROM user_scheduler_jobs
 ORDER BY job_name;

-- did they actually run?
SELECT job_name, status, actual_start_date, error#
  FROM user_scheduler_job_run_details
 ORDER BY actual_start_date DESC
 FETCH FIRST 20 ROWS ONLY;
 

INSERT INTO vacant_jobs (title, description, expires_at)
VALUES ('Watch Me', 'THIS WILL EXPIRE SOON', SYSTIMESTAMP + INTERVAL '2' MINUTE);
COMMIT;

SELECT description FROM vacant_jobs WHERE title = 'Watch Me';

SELECT * FROM vacant_jobs          WHERE title = 'Watch Me';  -- gone
SELECT * FROM jobs_posting_archive WHERE title = 'Watch Me';  -- here

--handing the rows to Java
CREATE OR REPLACE PROCEDURE get_pending_notifications (
    p_result OUT SYS_REFCURSOR
)
IS
BEGIN
    OPEN p_result FOR
        SELECT notification_id, job_id, subject, body, created_at
          FROM notification
         WHERE status = 'PENDING'
         ORDER BY created_at;
END get_pending_notifications;
/
SHOW ERRORS

--procedure for Java to mark a row sent
CREATE OR REPLACE PROCEDURE mark_notification_sent (
    p_notification_id IN NUMBER
)
IS
BEGIN
    UPDATE notification
       SET status = 'SENT', sent_at = SYSTIMESTAMP
     WHERE notification_id = p_notification_id;
    COMMIT;
END mark_notification_sent;
/