-- CREATE vacant_jobs table --

CREATE TABLE vacant_jobs (
    job_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    job_title VARCHAR2(150) NOT NULL,
    description VARCHAR2(1000) NOT NULL,
    posted_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    is_active CHAR(1) DEFAULT 'Y' NOT NULL,

    CONSTRAINT pk_vacant_jobs
        PRIMARY KEY (job_id),

    CONSTRAINT chk_vacant_jobs_active
        CHECK (is_active IN ('Y', 'N')),

    CONSTRAINT chk_vacant_jobs_expiry
        CHECK (expires_at > posted_at)
);


DESC vacant_jobs;

-- CREATE jobs_posting_archive table --
CREATE TABLE jobs_posting_archive (
    archive_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    job_id NUMBER NOT NULL,
    job_title VARCHAR2(150) NOT NULL,
    description VARCHAR2(1000) NOT NULL,
    posted_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    archived_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_jobs_posting_archive
        PRIMARY KEY (archive_id),

    CONSTRAINT uq_archive_job
        UNIQUE (job_id)
);



-- CREATE notifications table-- 

CREATE TABLE notifications (
    notification_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    subject VARCHAR2(200) NOT NULL,
    body VARCHAR2(2000) NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    sent_at TIMESTAMP,

    CONSTRAINT pk_notifications
        PRIMARY KEY (notification_id),

    CONSTRAINT chk_notification_status
        CHECK (status IN ('PENDING', 'SENT'))
);



-- CREATE job_applications table -- 
CREATE TABLE job_applications (
    application_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    job_id NUMBER NOT NULL,
    applicant_name VARCHAR2(150) NOT NULL,
    applicant_email VARCHAR2(200) NOT NULL,
    applied_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_job_applications
        PRIMARY KEY (application_id),

    CONSTRAINT fk_applications_job
        FOREIGN KEY (job_id)
        REFERENCES vacant_jobs(job_id)
        ON DELETE CASCADE
);


-- Verify the creation of the tables 
SELECT table_name FROM user_tables
WHERE table_name IN (
    'VACANT_JOBS',
    'JOB_APPLICATIONS',
    'JOBS_POSTING_ARCHIVE',
    'NOTIFICATIONS'
)
ORDER BY table_name;


-- SEED DATA --
-- Insert Vacancy 1 (Normal):
INSERT INTO vacant_jobs ( job_title,         description,                                    expires_at )
VALUES                  ( 'Java Developer', 'Develop and maintain Spring Boot applications', SYSTIMESTAMP + INTERVAL '1' DAY);


-- Insert Vacancy 2 (uppercase description):
INSERT INTO vacant_jobs ( job_title,            description,                                              expires_at )
VALUES                  ( 'Database Developer', 'STRONG PL/SQL AND ORACLE DATABASE EXPERIENCE REQUIRED',  SYSTIMESTAMP + INTERVAL '1' DAY);


-- Insert Vacancy 3 (Expires soon):
INSERT INTO vacant_jobs ( job_title,      description,                expires_at )
VALUES                  ( 'QA Engineer',  'Testing web applications', SYSTIMESTAMP + INTERVAL '10' MINUTE);

COMMIT;

-- Check the rows inserted to the table vacant_jobs
SELECT job_id, job_title, description, posted_at, expires_at, is_active FROM vacant_jobs;


-- Add three candidates to one job

SELECT job_id, job_title
FROM vacant_jobs;


INSERT INTO job_applications ( job_id, applicant_name, applicant_email )
VALUES                       ( 1,      'Ahmed Ali',   'ahmed@example.com');

INSERT INTO job_applications ( job_id, applicant_name, applicant_email )
VALUES                       ( 1,      'Sara Mohammed','sara@example.com' );

INSERT INTO job_applications ( job_id, applicant_name, applicant_email )
VALUES                       ( 1,      'Muna Khalid',  'muna@example.com' );

COMMIT;


SELECT * FROM job_applications;


-- Test the many-to-one relationship between vacant_jobs and job_applications

SELECT j.job_id, j.job_title,
    COUNT(a.application_id) AS applicant_count
FROM vacant_jobs j
LEFT JOIN job_applications a ON j.job_id = a.job_id
GROUP BY j.job_id, j.job_title;



-- =================================
--  REGISTER NOTIFICATION PROCEDURE
-- =================================

CREATE OR REPLACE PROCEDURE register_notification (
    p_subject IN VARCHAR2,
    p_body    IN VARCHAR2
)
AS
BEGIN

    INSERT INTO notifications (
        subject,
        body
    )
    VALUES (
        p_subject,
        p_body
    );

END register_notification;
/


-- check errors 
SHOW ERRORS PROCEDURE register_notification;



SELECT object_name, object_type, status
FROM user_objects WHERE object_name = 'REGISTER_NOTIFICATION';


-- Test the procedure 
BEGIN
    register_notification( 'Procedure Test', 'Testing register_notification directly.');
END;
/

SELECT notification_id, subject, body, created_at, status, sent_at
FROM notifications ORDER BY notification_id;  

-- After testing, clean the test notification
DELETE FROM notifications WHERE subject = 'Procedure Test';

COMMIT;


-- =======================
-- VACANCY POSTED TRIGGER
-- =======================

CREATE OR REPLACE TRIGGER trg_vacancy_posted
AFTER INSERT ON vacant_jobs
FOR EACH ROW
BEGIN
    register_notification(
        'New vacancy posted: ' || :NEW.job_title,
        'Job ID ' || :NEW.job_id ||
        ' - ' || :NEW.job_title ||
        ' has been posted and expires at ' ||
        TO_CHAR(
            :NEW.expires_at,
            'DD-MON-YYYY HH24:MI:SS'
        )
    );
END;
/


SHOW ERRORS TRIGGER trg_vacancy_posted;


-- HR posts one vacancy

SELECT COUNT(*) FROM notifications; -- result is 0, there is no notification

-- HR performs their one manual action(Add a vacancy):
INSERT INTO vacant_jobs ( job_title, description, expires_at )
VALUES ( 'Backend Developer', 'Build REST services using Java and Spring Boot', SYSTIMESTAMP + INTERVAL '30' MINUTE );

COMMIT;

-- Verify the vacancy
SELECT job_id, job_title, description, posted_at, expires_at, is_active
FROM vacant_jobs WHERE job_title = 'Backend Developer';


-- Verify the notification
SELECT notification_id, subject, body, created_at, status, sent_at
FROM notifications ORDER BY notification_id DESC;



-- Test transaction behavior
INSERT INTO vacant_jobs ( job_title, description, expires_at )
VALUES ( 'Rollback Test Job', 'This job should not survive', SYSTIMESTAMP + INTERVAL '1' DAY );

ROLLBACK;

SELECT *
FROM vacant_jobs
WHERE job_title = 'Rollback Test Job';

SELECT *
FROM notifications
WHERE subject LIKE '%Rollback Test Job%';

-- The aboved test proves trigger/procedure participates in the same transaction
-- ==================================================================================


-- Check trigger status
SELECT trigger_name, triggering_event, status
FROM user_triggers WHERE trigger_name = 'TRG_VACANCY_POSTED'; -- Output : Status = ENABLED



INSERT INTO vacant_jobs (
    job_title,
    description,
    expires_at
)
VALUES (
    'Spring Boot Developer',
    'Develop backend APIs',
    SYSTIMESTAMP + INTERVAL '30' MINUTE
);

COMMIT;

SELECT *
FROM notifications
ORDER BY notification_id DESC;


-- ============================
-- Section B - THE EDIT
-- ============================


-- Custome lowercase function

CREATE OR REPLACE FUNCTION custom_lowercase (
    p_text IN VARCHAR2
)
RETURN VARCHAR2
AS
    v_result VARCHAR2(32767) := '';
    v_char   CHAR(1);
BEGIN
    IF p_text IS NULL THEN
        RETURN NULL;
    END IF;
    FOR i IN 1 .. LENGTH(p_text)
    LOOP
        v_char := SUBSTR(p_text, i, 1);
        IF ASCII(v_char) BETWEEN ASCII('A') AND ASCII('Z') THEN

            v_result :=
                v_result ||
                CHR(ASCII(v_char) + 32);
        ELSE
            v_result :=
                v_result ||
                v_char;
        END IF;
    END LOOP;
    RETURN v_result;
END custom_lowercase;
/


SHOW ERRORS FUNCTION custom_lowercase;

-- Test the function

SELECT custom_lowercase('HELLO WORLD') FROM dual; -- OUTPUT: hello world 

SELECT custom_lowercase('already lower case') FROM dual; --  OUTPUT: already lower case



-- Step 05 — Procedure 

CREATE OR REPLACE PROCEDURE process_job_description (
    p_original_description IN  VARCHAR2,
    p_clean_description    OUT VARCHAR2
)
AS
BEGIN

    p_clean_description :=
        custom_lowercase(p_original_description);

END process_job_description;
/

-- Test the procedure

SET SERVEROUTPUT ON; 


DECLARE
    v_result VARCHAR2(1000);
BEGIN

    process_job_description(
        'THIS Is My VACANCY Description',
        v_result
    );

    DBMS_OUTPUT.PUT_LINE(v_result);

END;
/



-- Step 05 — UPDATE trigger

CREATE OR REPLACE TRIGGER trg_vacancy_description
BEFORE UPDATE OF description
ON vacant_jobs
FOR EACH ROW
DECLARE
    v_clean_description VARCHAR2(1000);
BEGIN

    process_job_description(
        :NEW.description,
        v_clean_description
    );

    :NEW.description :=
        v_clean_description;

END;
/



-- Step 04 — Test the human update ( Test B -- THE EDIT)

SELECT job_id, job_title, description FROM vacant_jobs ORDER BY job_id;

-- Choose JOB_ID = 1 

UPDATE vacant_jobs SET description = 'MUST HAVE JAVA SPRING BOOT AND ORACLE EXPERIENCE' WHERE job_id = 1;

COMMIT;

SELECT job_id, job_title, description FROM vacant_jobs WHERE job_id = 1; -- The Output of the description shows : must have java spring boot and oracle experience  



-- Check the object status , all should be valid

SELECT object_name, object_type, status FROM user_objects
WHERE object_name IN ( 'CUSTOM_LOWERCASE', 'PROCESS_JOB_DESCRIPTION', 'TRG_VACANCY_DESCRIPTION')
ORDER BY object_type, object_name;


-- ===================
-- C.07 — Time Runs Out
-- ===================

-- CREATE expire_vacancies PROCEDURE

CREATE OR REPLACE PROCEDURE expire_vacancies
AS
    v_expired_count NUMBER;
BEGIN

    UPDATE vacant_jobs
    SET is_active = 'N'
    WHERE is_active = 'Y'
      AND expires_at <= SYSTIMESTAMP;

    v_expired_count := SQL%ROWCOUNT;

    DBMS_OUTPUT.PUT_LINE(
        'Vacancies expired: ' || v_expired_count
    );

END expire_vacancies;
/


-- Test the procedure manually

-- create a vacancy that expires shortly
INSERT INTO vacant_jobs ( job_title, description, expires_at )
VALUES ( 'Temporary Test Vacancy', 'THIS JOB WILL EXPIRE SOON', SYSTIMESTAMP + INTERVAL '1' MINUTE );

COMMIT;

-- Check it
SELECT job_id, job_title, expires_at, is_active FROM vacant_jobs WHERE job_title = 'Temporary Test Vacancy'; -- IS_ACTIVE: Y 



SET SERVEROUTPUT ON;

BEGIN
    expire_vacancies;
END;
/

SELECT job_id, job_title, expires_at, is_active FROM vacant_jobs WHERE job_title = 'Temporary Test Vacancy'; -- IS_ACTIVE: N 


-- Create the scheduled job

BEGIN
    DBMS_SCHEDULER.CREATE_JOB (
        job_name        => 'JOB_EXPIRE_VACANCIES',
        job_type        => 'STORED_PROCEDURE',
        job_action      => 'EXPIRE_VACANCIES',
        start_date      => SYSTIMESTAMP,
        repeat_interval => 'FREQ=MINUTELY;INTERVAL=1',
        enabled         => TRUE,
        auto_drop       => FALSE
    );
END;
/


-- Verify the scheduled job creation
SELECT
    job_name,
    enabled,
    state,
    repeat_interval
FROM user_scheduler_jobs
WHERE job_name = 'JOB_EXPIRE_VACANCIES';

-- =========================
-- C.08 — The Post Is Filed
-- =========================

-- Create archive_expired_vacancies procedure 

CREATE OR REPLACE PROCEDURE archive_expired_vacancies
AS
    v_archive_count NUMBER;
BEGIN

    INSERT INTO jobs_posting_archive (
        job_id,
        job_title,
        description,
        posted_at,
        expires_at
    )
    SELECT
        j.job_id,
        j.job_title,
        j.description,
        j.posted_at,
        j.expires_at
    FROM vacant_jobs j
    WHERE j.is_active = 'N'
      AND NOT EXISTS (
          SELECT 1
          FROM jobs_posting_archive a
          WHERE a.job_id = j.job_id
      );

    v_archive_count := SQL%ROWCOUNT;

    DBMS_OUTPUT.PUT_LINE(
        'Vacancies archived: ' || v_archive_count
    );

END archive_expired_vacancies;
/

-- Test archive manually

SELECT job_id, job_title, is_active FROM vacant_jobs WHERE is_active = 'N';



BEGIN
    archive_expired_vacancies;
END;
/


SELECT archive_id,job_id,job_title, description, posted_at, expires_at, archived_at
FROM jobs_posting_archive ORDER BY archive_id; -- INACTIVE vacancy appears 

-- ============================
-- C.09 — The Board Is Cleared
-- ============================

-- Create purge_archived_vacancies procedure


CREATE OR REPLACE PROCEDURE purge_archived_vacancies
AS
    v_purge_count NUMBER;
BEGIN

    DELETE FROM vacant_jobs j
    WHERE j.is_active = 'N'
      AND EXISTS (
          SELECT 1
          FROM jobs_posting_archive a
          WHERE a.job_id = j.job_id
      );

    v_purge_count := SQL%ROWCOUNT;

    DBMS_OUTPUT.PUT_LINE(
        'Vacancies purged: ' || v_purge_count
    );

END purge_archived_vacancies;
/



-- Test purge

BEGIN
    purge_archived_vacancies;
END;
/

SELECT * FROM vacant_jobs WHERE job_id = 3; -- OUTPUT: no rows selected 



SELECT * FROM jobs_posting_archive WHERE job_id = 3; -- OUTPUT: Returns the test row


-- Create a coordinating procedure

-- C:08-09  ARCHIVE THEN PURGE


CREATE OR REPLACE PROCEDURE archive_and_purge_vacancies
AS
BEGIN
    archive_expired_vacancies;
    purge_archived_vacancies;
END archive_and_purge_vacancies;
/


-- Create the archive/purge scheduled job

BEGIN
    DBMS_SCHEDULER.CREATE_JOB (
        job_name        => 'JOB_ARCHIVE_AND_PURGE',
        job_type        => 'STORED_PROCEDURE',
        job_action      => 'ARCHIVE_AND_PURGE_VACANCIES',
        start_date      => SYSTIMESTAMP,
        repeat_interval => 'FREQ=MINUTELY;INTERVAL=1',
        enabled         => TRUE,
        auto_drop       => FALSE
    );
END;
/
-- ====================================
-- C.10 — Sweep Tidies the Whole Board
-- ====================================


-- Create sweep_job_descriptions IMPLICIT CURSOR

CREATE OR REPLACE PROCEDURE sweep_job_descriptions
AS
    v_clean_description VARCHAR2(1000);
    v_processed_count   NUMBER := 0;
BEGIN
    FOR job_rec IN (
        SELECT
            job_id,
            description
        FROM vacant_jobs
        WHERE is_active = 'Y'
        ORDER BY job_id
    )
    LOOP
        v_clean_description :=
            custom_lowercase(job_rec.description);

        UPDATE vacant_jobs
        SET description = v_clean_description
        WHERE job_id = job_rec.job_id;

        v_processed_count :=
            v_processed_count + 1;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE(
        'Live descriptions processed: ' ||
        v_processed_count
    );
END sweep_job_descriptions;
/


--  Test the sweep


-- tmporary disable the update trigger for isolated testing

ALTER TRIGGER trg_vacancy_description DISABLE;

UPDATE vacant_jobs
SET description = 'THIS IS DIRTY UPPERCASE DATA'
WHERE job_id = 1;

COMMIT;

ALTER TRIGGER trg_vacancy_description ENABLE;


SELECT job_id, description FROM vacant_jobs WHERE job_id = 1; -- OUTPUT: THIS IS DIRTY UPPERCASE DATA


-- Run the sweep manually 
BEGIN
    sweep_job_descriptions;
END;
/



SELECT job_id, description FROM vacant_jobs WHERE job_id = 1; -- OUTPUT: this is dirty uppercase data


-- Schedule the sweep

BEGIN
    DBMS_SCHEDULER.CREATE_JOB (
        job_name        => 'JOB_DESCRIPTION_SWEEP',
        job_type        => 'STORED_PROCEDURE',
        job_action      => 'SWEEP_JOB_DESCRIPTIONS',
        start_date      => SYSTIMESTAMP,
        repeat_interval => 'FREQ=MINUTELY;INTERVAL=5',
        enabled         => TRUE,
        auto_drop       => FALSE
    );
END;
/


-- View all our scheduled jobs
SELECT job_name, enabled, state, repeat_interval, last_start_date, next_run_date
FROM user_scheduler_jobs
WHERE job_name IN ( 'JOB_EXPIRE_VACANCIES', 'JOB_ARCHIVE_AND_PURGE', 'JOB_DESCRIPTION_SWEEP' )
ORDER BY job_name;


BEGIN
    DBMS_SCHEDULER.RUN_JOB(
        job_name            => 'JOB_DESCRIPTION_SWEEP',
        use_current_session => TRUE
    );
END;
/



-- ================
-- Part D 
-- ================

-- D.12 — One Digest a Day

-- Create the daily digest implicit cursor

CREATE OR REPLACE PROCEDURE create_daily_application_digest
AS
    v_digest_count NUMBER := 0;
BEGIN

    FOR digest_rec IN (
        SELECT
            j.job_id,
            j.description,
            COUNT(a.application_id) AS application_count
        FROM vacant_jobs j
        LEFT JOIN job_applications a
            ON a.job_id = j.job_id
        WHERE j.is_active = 'Y'
        GROUP BY
            j.job_id,
            j.description
        ORDER BY
            j.job_id
    )
    LOOP

        DECLARE
            v_existing_count NUMBER;
        BEGIN

            SELECT COUNT(*)
            INTO v_existing_count
            FROM notifications
            WHERE subject =
                    'Daily application digest - Job ' ||
                    digest_rec.job_id
              AND created_at >=
                    CAST(TRUNC(SYSDATE) AS TIMESTAMP)
              AND created_at <
                    CAST(TRUNC(SYSDATE) + 1 AS TIMESTAMP);

            IF v_existing_count = 0 THEN

                register_notification(
                    'Daily application digest - Job ' ||
                        digest_rec.job_id,

                    'Job ID: ' ||
                        digest_rec.job_id ||
                    ' | Description: ' ||
                        digest_rec.description ||
                    ' | Applications: ' ||
                        digest_rec.application_count
                );

                v_digest_count :=
                    v_digest_count + 1;

            END IF;

        END;

    END LOOP;

    DBMS_OUTPUT.PUT_LINE(
        'New digest notifications created: ' ||
        v_digest_count
    );

END create_daily_application_digest;
/

-- Test the digest procedure manually 
SET SERVEROUTPUT ON;

BEGIN
    create_daily_application_digest;
END;
/


SELECT notification_id, subject, body, status FROM notifications
WHERE subject LIKE 'Daily application digest%' ORDER BY notification_id;



-- verify explicitly -- one notification created
SELECT COUNT(*)
INTO v_existing_count
FROM notifications
WHERE subject =
        'Daily application digest - Job ' ||
        digest_rec.job_id
  AND created_at >=
        CAST(TRUNC(SYSDATE) AS TIMESTAMP)
  AND created_at <
        CAST(TRUNC(SYSDATE) + 1 AS TIMESTAMP);
        

-- Create fourth scheduler

BEGIN
    DBMS_SCHEDULER.CREATE_JOB (
        job_name        => 'JOB_DAILY_APPLICATION_DIGEST',
        job_type        => 'STORED_PROCEDURE',
        job_action      => 'CREATE_DAILY_APPLICATION_DIGEST',
        start_date      => SYSTIMESTAMP,
        repeat_interval =>
            'FREQ=DAILY;BYHOUR=8;BYMINUTE=0;BYSECOND=0',
        enabled         => TRUE,
        auto_drop       => FALSE
    );
END;
/


-- Run the scheduler manually
BEGIN
    DBMS_SCHEDULER.RUN_JOB(
        job_name            =>
            'JOB_DAILY_APPLICATION_DIGEST',
        use_current_session => TRUE
    );
END;
/

-- Now check 
SELECT notification_id, subject, body, status FROM notifications
WHERE subject LIKE 'Daily application digest%' ORDER BY notification_id;



-- Four clocks with stated intervals
SELECT job_name, enabled, state, repeat_interval, last_start_date, next_run_date
FROM user_scheduler_jobs
WHERE job_name IN (
    'JOB_EXPIRE_VACANCIES',
    'JOB_ARCHIVE_AND_PURGE',
    'JOB_DESCRIPTION_SWEEP',
    'JOB_DAILY_APPLICATION_DIGEST'
) ORDER BY job_name;


        
SELECT
    subject,
    body
FROM notifications
WHERE subject LIKE
    'Daily application digest%'
ORDER BY notification_id DESC;




-- ==================
-- GET PENDING NOTIFICATIONS
--     EXPLICIT REF CURSOR
-- ==================


CREATE OR REPLACE PROCEDURE get_pending_notifications (
    p_notifications OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN p_notifications FOR
        SELECT
            notification_id,
            subject,
            body,
            created_at
        FROM notifications
        WHERE status = 'PENDING'
        ORDER BY notification_id;

END get_pending_notifications;
/

-- Test the procedure 

DESC get_pending_notifications;

VARIABLE rc REFCURSOR;

BEGIN
    get_pending_notifications(:rc);
END;
/

PRINT rc;


-- CREATE  mark_notification_sent 

CREATE OR REPLACE PROCEDURE mark_notification_sent (
    p_notification_id IN NUMBER
)
AS
BEGIN

    UPDATE notifications
    SET
        status  = 'SENT',
        sent_at = SYSTIMESTAMP
    WHERE notification_id = p_notification_id
      AND status = 'PENDING';

END mark_notification_sent;
/


SHOW ERRORS PROCEDURE mark_notification_sent;


SELECT notification_id, subject, status, sent_at FROM notifications
WHERE status = 'PENDING' ORDER BY notification_id;


BEGIN
    mark_notification_sent(5);
END;
/

COMMIT;


SELECT notification_id, status, sent_at
FROM notifications WHERE notification_id = 5;


----------------------------------
VARIABLE rc REFCURSOR;

BEGIN
    get_pending_notifications(:rc);
END;
/

PRINT rc;
------------------------------------ Run full 




SELECT
    notification_id,
    subject,
    body,
    created_at,
    status
FROM notifications
WHERE status = 'PENDING'
ORDER BY notification_id;

SELECT
    notification_id,
    subject,
    status,
    sent_at
FROM notifications
ORDER BY notification_id;




INSERT INTO vacant_jobs (
    job_title,
    description,
    expires_at
)
VALUES (
    'Slack End To End Test',
    'TESTING THE COMPLETE DATABASE TO SLACK FLOW',
    SYSTIMESTAMP + INTERVAL '1' DAY
);

COMMIT;


SELECT
    notification_id,
    subject,
    status,
    sent_at
FROM notifications
WHERE subject LIKE '%Slack End To End Test%'
ORDER BY notification_id DESC;
