SET DEFINE OFF;

CREATE TABLE vacant_jobs (
    job_id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    job_title       VARCHAR2(150) NOT NULL,
    description     VARCHAR2(2000) NOT NULL,
    expires_at      TIMESTAMP NOT NULL,
    active_flag     CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_vacant_jobs
        PRIMARY KEY (job_id),

    CONSTRAINT ck_vacant_jobs_active
        CHECK (active_flag IN ('Y', 'N'))
);

CREATE TABLE jobs_posting_archive (
    job_id          NUMBER,
    job_title       VARCHAR2(150) NOT NULL,
    description     VARCHAR2(2000) NOT NULL,
    expires_at      TIMESTAMP NOT NULL,
    created_at      TIMESTAMP NOT NULL,

    CONSTRAINT pk_jobs_posting_archive
        PRIMARY KEY (job_id)
);

CREATE TABLE job_applications (
    application_id  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    job_id          NUMBER NOT NULL,
    applicant_name  VARCHAR2(150) NOT NULL,
    applicant_email VARCHAR2(254) NOT NULL,
    applied_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_job_applications
        PRIMARY KEY (application_id),

    CONSTRAINT fk_applications_vacancy
        FOREIGN KEY (job_id)
        REFERENCES vacant_jobs (job_id),

    CONSTRAINT uq_application_per_job
        UNIQUE (job_id, applicant_email)
);

-- Candidate applications are archived before their vacancy is purged so recruitment history is not lost.
CREATE TABLE job_applications_archive (
    application_id  NUMBER,
    job_id          NUMBER NOT NULL,
    applicant_name  VARCHAR2(150) NOT NULL,
    applicant_email VARCHAR2(254) NOT NULL,
    applied_at      TIMESTAMP NOT NULL,

    CONSTRAINT pk_applications_archive
        PRIMARY KEY (application_id),

    CONSTRAINT fk_app_archive_job_archive
        FOREIGN KEY (job_id)
        REFERENCES jobs_posting_archive (job_id),

    CONSTRAINT uq_archived_application
        UNIQUE (job_id, applicant_email)
);

-- Notifications remain independent from vacancy rows because a daily digest can describe several jobs and must survive vacancy purging.
CREATE TABLE notifications (
    notification_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    notification_type VARCHAR2(30) NOT NULL,
    subject            VARCHAR2(200) NOT NULL,
    body               CLOB NOT NULL,
    status             VARCHAR2(10) DEFAULT 'PENDING' NOT NULL,
    dedup_key          VARCHAR2(200),
    attempt_count      NUMBER DEFAULT 0 NOT NULL,
    created_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    sent_at            TIMESTAMP,

    CONSTRAINT pk_notifications
        PRIMARY KEY (notification_id),

    CONSTRAINT uq_notifications_dedup
        UNIQUE (dedup_key),

    CONSTRAINT ck_notification_type
        CHECK (notification_type IN ('JOB_POSTED', 'DAILY_DIGEST')),

    CONSTRAINT ck_notification_status
        CHECK (status IN ('PENDING', 'SENT', 'FAILED')),

    CONSTRAINT ck_notification_attempts
        CHECK (attempt_count >= 0),

    CONSTRAINT ck_notification_sent_time
        CHECK (
            (status = 'SENT' AND sent_at IS NOT NULL)
            OR
            (status IN ('PENDING', 'FAILED') AND sent_at IS NULL)
        )
);

CREATE INDEX ix_vacant_jobs_expiry
    ON vacant_jobs (active_flag, expires_at);

CREATE INDEX ix_notifications_queue
    ON notifications (status, created_at, notification_id);

PROMPT Schema objects created successfully.
