spring.application.name=vacancy-loop-consumer

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

slack.webhook.url=${SLACK_WEBHOOK_URL}

# this app is a one-shot consumer, not a web api - no need for a web server
spring.main.web-application-type=none