-- Creates all tables, keys, relationships and constraints
-- required for the Vacancy Loop project.
------------------------------------------------------------
-- USERS


CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    username VARCHAR2(50) NOT NULL UNIQUE,

    full_name VARCHAR2(100) NOT NULL,

    email VARCHAR2(100) NOT NULL UNIQUE
        CHECK (email LIKE '%_@_%._%'),

    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    is_active CHAR(1) DEFAULT 'Y' NOT NULL
        CHECK (is_active IN ('Y', 'N'))
);


------------------------------------------------------------
-- VACANT JOBS

CREATE TABLE vacant_jobs (
    job_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    posted_by NUMBER NOT NULL,

    title VARCHAR2(200) NOT NULL,

    description VARCHAR2(4000) NOT NULL,

    location VARCHAR2(200),

    job_type VARCHAR2(50),

    is_active CHAR(1) DEFAULT 'Y' NOT NULL
        CHECK (is_active IN ('Y', 'N')),

    posted_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    expires_at TIMESTAMP NOT NULL,

    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT fk_job_posted_by
        FOREIGN KEY (posted_by)
        REFERENCES users(user_id)
);


------------------------------------------------------------
-- JOB APPLICATIONS

CREATE TABLE job_applications (
    application_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    job_id NUMBER NOT NULL,

    applicant_name VARCHAR2(200) NOT NULL,

    applicant_email VARCHAR2(200) NOT NULL
        CHECK (applicant_email LIKE '%_@_%._%'),

    resume_url VARCHAR2(500),

    status VARCHAR2(20) DEFAULT 'NEW' NOT NULL
        CHECK (status IN ('NEW', 'REVIEWED', 'ACCEPTED', 'REJECTED')),

    applied_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT fk_application_job
        FOREIGN KEY (job_id)
        REFERENCES vacant_jobs(job_id),

    CONSTRAINT uq_job_applicant
        UNIQUE (job_id, applicant_email)
);


------------------------------------------------------------
-- NOTIFICATIONS

CREATE TABLE notifications (
    notification_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    subject VARCHAR2(500) NOT NULL,

    body CLOB NOT NULL,

    type VARCHAR2(30) NOT NULL,

    related_job_id NUMBER,

    status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL
        CHECK (status IN ('PENDING', 'SENT', 'FAILED')),

    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    sent_at TIMESTAMP,

    attempt_count NUMBER DEFAULT 0 NOT NULL
        CHECK (attempt_count >= 0),

    last_error VARCHAR2(1000),

    created_by VARCHAR2(30),

    CONSTRAINT fk_notification_job
        FOREIGN KEY (related_job_id)
        REFERENCES vacant_jobs(job_id)
);


------------------------------------------------------------
-- JOB POSTING ARCHIVE

CREATE TABLE jobs_posting_archive (
    archive_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    job_id NUMBER NOT NULL,

    posted_by NUMBER NOT NULL,

    title VARCHAR2(200) NOT NULL,

    description VARCHAR2(4000) NOT NULL,

    location VARCHAR2(200),

    job_type VARCHAR2(50),

    posted_at TIMESTAMP,

    expires_at TIMESTAMP,

    updated_at TIMESTAMP,

    archived_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT uq_archived_job
        UNIQUE (job_id)
);


------------------------------------------------------------
-- VERIFY TABLE CREATION

SELECT table_name FROM user_tables
WHERE table_name IN (
    'USERS',
    'VACANT_JOBS',
    'JOB_APPLICATIONS',
    'NOTIFICATIONS',
    'JOBS_POSTING_ARCHIVE'
)
ORDER BY table_name;


------------------------------------------------------------
-- VERIFY CONSTRAINTS

SELECT table_name, constraint_name, constraint_type, status FROM user_constraints
WHERE table_name IN (
    'USERS',
    'VACANT_JOBS',
    'JOB_APPLICATIONS',
    'NOTIFICATIONS',
    'JOBS_POSTING_ARCHIVE'
)
ORDER BY table_name, constraint_type;