spring.application.name=vacancy-loop-consumer
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

slack.webhook.url=${SLACK_WEBHOOK_URL}
consumer.poll-interval-ms=60000
consumer.initial-delay-ms=3000