
-- tables

-- clean slate, drop old tables if they exist
BEGIN
  FOR r IN (
    SELECT table_name FROM user_tables
    WHERE table_name IN ('JOB_APPLICATIONS','JOBS_POSTING_ARCHIVE','NOTIFICATIONS','VACANT_JOBS')
  ) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || r.table_name || ' CASCADE CONSTRAINTS PURGE';
  END LOOP;
END;
/

-- the live job board, HR inserts here
create table vacant_jobs (
  job_id       number generated by default as identity primary key,
  title        varchar2(150) not null,
  description  varchar2(2000) not null,
  posted_at    timestamp default systimestamp not null,
  expires_at   timestamp not null,
  job_status   varchar2(10) default 'ACTIVE' not null
               check (job_status in ('ACTIVE','EXPIRED','ARCHIVED'))
);

-- same shape as vacant_jobs, minus job_status
create table jobs_posting_archive (
  job_id       number primary key,
  title        varchar2(150) not null,
  description  varchar2(2000) not null,
  posted_at    timestamp not null,
  expires_at   timestamp not null,
  archived_at  timestamp default systimestamp not null
);

-- every message the system creates lands here
create table notifications (
  notification_id  number generated by default as identity primary key,
  subject          varchar2(200) not null,
  body             varchar2(2000) not null,
  created_at       timestamp default systimestamp not null,
  sent_flag        char(1) default 'N' not null
                   check (sent_flag in ('Y','N'))
);

-- candidates who applied, many rows can point to one job
create table job_applications (
  application_id  number generated by default as identity primary key,
  job_id          number not null references vacant_jobs(job_id),
  applicant_name  varchar2(150) not null,
  applied_at      timestamp default systimestamp not null
);

-- seed data


insert into vacant_jobs (title, description, posted_at, expires_at, job_status)
values ('HR Coordinator', 'Handles onboarding and offboarding for new hires', systimestamp, systimestamp + interval '30' day, 'ACTIVE');

insert into vacant_jobs (title, description, posted_at, expires_at, job_status)
values ('QA Engineer', 'MANUAL AND AUTOMATED TESTING FOR THE CORE PRODUCT', systimestamp, systimestamp + interval '10' day, 'ACTIVE');

insert into vacant_jobs (title, description, posted_at, expires_at, job_status)
values ('Graphic Designer', 'Create visual content for social media campaigns', systimestamp, systimestamp + interval '5' day, 'ACTIVE');

insert into vacant_jobs (title, description, posted_at, expires_at, job_status)
values ('Sales Executive', 'MEET MONTHLY SALES TARGETS AND BUILD CLIENT RELATIONSHIPS', systimestamp, systimestamp + interval '20' day, 'ACTIVE');

insert into vacant_jobs (title, description, posted_at, expires_at, job_status)
values ('Warehouse Supervisor', 'Oversee inventory and daily warehouse operations', systimestamp, systimestamp + interval '45' day, 'ACTIVE');

-- a job that expires soon, to watch the full lifecycle happen quickly
insert into vacant_jobs (title, description, posted_at, expires_at, job_status)
values ('Backend Developer', 'WE NEED SOMEONE WHO KNOWS PL/SQL WELL', systimestamp, systimestamp + interval '2' minute, 'ACTIVE');

commit;

-- applicants spread across different jobs
insert into job_applications (job_id, applicant_name)
select job_id, 'Huda Al-Riyami' from vacant_jobs where title = 'QA Engineer';
insert into job_applications (job_id, applicant_name)
select job_id, 'Anwar Al-Zadjali' from vacant_jobs where title = 'QA Engineer';
insert into job_applications (job_id, applicant_name)
select job_id, 'Rashid Al-Mamari' from vacant_jobs where title = 'QA Engineer';
insert into job_applications (job_id, applicant_name)
select job_id, 'Layla Al-Harthy' from vacant_jobs where title = 'HR Coordinator';

commit;


-- part a - new job notification


-- writes one notification row, reusable from anywhere
create or replace procedure register_notification (
  p_subject in varchar2,
  p_body    in varchar2
)
as
begin
  insert into notifications (subject, body)
  values (p_subject, p_body);
end;
/

-- fires automatically every time HR inserts a new job
create or replace trigger trg_new_job_notify
after insert on vacant_jobs
for each row
begin
  -- ask the procedure to write the notification for us
  register_notification(
    'New job posted: ' || :new.title,
    'Job #' || :new.job_id || ' "' || :new.title || '" was posted and expires at ' || to_char(:new.expires_at, 'YYYY-MM-DD HH24:MI')
  );
end;
/


-- part b - lowercase description


-- converts text to lowercase using a matching card of letters, no oracle lower function
create or replace function to_lower_custom (p_text in varchar2) return varchar2
as
  v_upper_card  varchar2(26) := 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
  v_lower_card  varchar2(26) := 'abcdefghijklmnopqrstuvwxyz';
  v_result      varchar2(2000) := '';
  v_char        char(1);
  v_position    number;
begin
  -- walk the text one letter at a time
  for i in 1 .. length(p_text) loop
    v_char := substr(p_text, i, 1);

    -- find this letter's spot on the uppercase card
    v_position := instr(v_upper_card, v_char);

    -- if we found it, swap in the matching letter from the lowercase card
    if v_position > 0 then
      v_char := substr(v_lower_card, v_position, 1);
    end if;

    v_result := v_result || v_char;
  end loop;

  return v_result;
end;
/

-- fires before update on description, so text is already lowercase when saved
create or replace trigger trg_lowercase_description
before update of description on vacant_jobs
for each row
begin
  :new.description := to_lower_custom(:new.description);
end;
/

-- part c - job lifecycle (expire, archive, purge, sweep)


-- moves jobs from ACTIVE to EXPIRED once their expiry time has passed
create or replace procedure expire_old_jobs
as
  v_counter number := 0;
begin
  for curr_rec_obj in (select job_id from vacant_jobs where job_status = 'ACTIVE' and expires_at < systimestamp) loop
    update vacant_jobs set job_status = 'EXPIRED' where job_id = curr_rec_obj.job_id;
    v_counter := v_counter + 1;
  end loop;
  commit;
  dbms_output.put_line(v_counter || ' jobs expired.');
end;
/

-- copies expired jobs into the archive table and marks them archived
create or replace procedure archive_expired_jobs
as
  v_counter number := 0;
begin
  for curr_rec_obj in (select job_id, title, description, posted_at, expires_at from vacant_jobs where job_status = 'EXPIRED') loop

    insert into jobs_posting_archive (job_id, title, description, posted_at, expires_at)
    values (curr_rec_obj.job_id, curr_rec_obj.title, curr_rec_obj.description, curr_rec_obj.posted_at, curr_rec_obj.expires_at);

    update vacant_jobs set job_status = 'ARCHIVED' where job_id = curr_rec_obj.job_id;

    v_counter := v_counter + 1;
  end loop;
  commit;
  dbms_output.put_line(v_counter || ' jobs archived.');
end;
/

-- deletes archived jobs from the board, along with their applications
create or replace procedure purge_archived_jobs
as
  v_counter number := 0;
begin
  for curr_rec_obj in (select job_id from vacant_jobs where job_status = 'ARCHIVED') loop

    delete from job_applications where job_id = curr_rec_obj.job_id;
    delete from vacant_jobs where job_id = curr_rec_obj.job_id;

    v_counter := v_counter + 1;
  end loop;
  commit;
  dbms_output.put_line(v_counter || ' jobs purged.');
end;
/

-- runs archiving then purging together, in the safe order
create or replace procedure archive_and_purge_jobs
as
begin
  archive_expired_jobs();
  purge_archived_jobs();
end;
/

-- walks every job still on the board and re-lowercases its description
-- safe to run again and again: already-lowercase text comes back unchanged
create or replace procedure sweep_all_descriptions
as
  v_counter number := 0;
begin
  for curr_rec_obj in (select job_id, description from vacant_jobs where job_status in ('ACTIVE','EXPIRED')) loop

    update vacant_jobs
    set    description = to_lower_custom(curr_rec_obj.description)
    where  job_id = curr_rec_obj.job_id;

    v_counter := v_counter + 1;
  end loop;
  commit;
  dbms_output.put_line(v_counter || ' descriptions swept.');
end;
/


-- part d - daily digest


-- once a day, counts applicants per job and writes one notification line per job
create or replace procedure daily_digest
as
  v_counter number := 0;
begin
  for curr_rec_obj in (
    select v.job_id, v.description, count(a.application_id) as applicant_count
    from   vacant_jobs v
    join   job_applications a on a.job_id = v.job_id
    group  by v.job_id, v.description
  ) loop

    register_notification(
      'Daily digest for job #' || curr_rec_obj.job_id,
      'Job #' || curr_rec_obj.job_id || ' "' || curr_rec_obj.description || '" received ' || curr_rec_obj.applicant_count || ' application(s) so far'
    );

    v_counter := v_counter + 1;
  end loop;
  commit;
  dbms_output.put_line(v_counter || ' digest lines written.');
end;
/


-- part e - explicit cursor for java


-- hands out all pending (not yet sent) notifications as a live result set for java to consume
create or replace procedure get_pending_notifications (
  p_cursor out sys_refcursor
)
as
begin
  open p_cursor for
    select notification_id, subject, body
    from   notifications
    where  sent_flag = 'N'
    order  by notification_id;
end;
/

-- called by java right after each slack post succeeds, one record at a time
create or replace procedure mark_notification_sent (
  p_notification_id in number
)
as
begin
  update notifications
  set    sent_flag = 'Y'
  where  notification_id = p_notification_id;
  commit;
end;
/


-- scheduled jobs


-- checks for expired jobs every minute
begin
  dbms_scheduler.create_job(
    job_name        => 'job_expire_old_jobs',
    job_type        => 'STORED_PROCEDURE',
    job_action      => 'expire_old_jobs',
    start_date      => systimestamp,
    repeat_interval => 'freq=minutely; interval=1',
    enabled         => true
  );
end;
/

-- archives then purges expired jobs every minute, in the safe order
begin
  dbms_scheduler.create_job(
    job_name        => 'job_archive_and_purge',
    job_type        => 'STORED_PROCEDURE',
    job_action      => 'archive_and_purge_jobs',
    start_date      => systimestamp,
    repeat_interval => 'freq=minutely; interval=1',
    enabled         => true
  );
end;
/

-- sweeps every job description every 5 minutes
begin
  dbms_scheduler.create_job(
    job_name        => 'job_sweep_descriptions',
    job_type        => 'STORED_PROCEDURE',
    job_action      => 'sweep_all_descriptions',
    start_date      => systimestamp,
    repeat_interval => 'freq=minutely; interval=5',
    enabled         => true
  );
end;
/

-- writes the daily digest once every 24 hours
begin
  dbms_scheduler.create_job(
    job_name        => 'job_daily_digest',
    job_type        => 'STORED_PROCEDURE',
    job_action      => 'daily_digest',
    start_date      => systimestamp,
    repeat_interval => 'freq=daily; byhour=9; byminute=0; bysecond=0',
    enabled         => true
  );
end;
/
