-- The Vacancy Loop
-- 01 - Database schema and sample data

CREATE TABLE vacant_jobs (
    job_id       NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    title        VARCHAR2(150) NOT NULL,
    description  VARCHAR2(1000) NOT NULL,
    posted_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    expires_at   TIMESTAMP NOT NULL,
    is_active    CHAR(1) DEFAULT 'Y' NOT NULL,

    CONSTRAINT chk_vacant_jobs_active
        CHECK (is_active IN ('Y', 'N')),

    CONSTRAINT chk_vacant_jobs_dates
        CHECK (expires_at > posted_at)
);

CREATE TABLE jobs_posting_archive (
    job_id       NUMBER PRIMARY KEY,
    title        VARCHAR2(150) NOT NULL,
    description  VARCHAR2(1000) NOT NULL,
    posted_at    TIMESTAMP NOT NULL,
    expires_at   TIMESTAMP NOT NULL
);

CREATE TABLE job_applications (
    application_id  NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    job_id           NUMBER NOT NULL,
    candidate_name   VARCHAR2(150) NOT NULL,
    candidate_email  VARCHAR2(200) NOT NULL,
    applied_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT fk_application_job
        FOREIGN KEY (job_id)
        REFERENCES vacant_jobs(job_id)
        ON DELETE CASCADE,

    CONSTRAINT uq_application_email
        UNIQUE (job_id, candidate_email)
);

CREATE TABLE notification (
    notification_id  NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    job_id            NUMBER,
    subject           VARCHAR2(200) NOT NULL,
    body              VARCHAR2(2000) NOT NULL,
    status            VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    sent_at           TIMESTAMP,

    CONSTRAINT fk_notification_job
        FOREIGN KEY (job_id)
        REFERENCES vacant_jobs(job_id)
        ON DELETE SET NULL,

    CONSTRAINT chk_notification_status
        CHECK (status IN ('PENDING', 'SENT'))
);

-- The archive intentionally has no foreign key to vacant_jobs.
-- Archived postings must remain after the original row is deleted.

INSERT INTO vacant_jobs (
    job_id,
    title,
    description,
    posted_at,
    expires_at,
    is_active
)
VALUES (
    101,
    'Database Developer',
    'BUILD AND MAINTAIN ORACLE DATABASE SYSTEMS',
    SYSTIMESTAMP - INTERVAL '1' DAY,
    SYSTIMESTAMP + INTERVAL '2' DAY,
    'Y'
);

INSERT INTO vacant_jobs (
    job_id,
    title,
    description,
    posted_at,
    expires_at,
    is_active
)
VALUES (
    102,
    'HR Assistant',
    'SUPPORT THE DAILY RECRUITMENT ACTIVITIES',
    SYSTIMESTAMP - INTERVAL '1' DAY,
    SYSTIMESTAMP + INTERVAL '10' MINUTE,
    'Y'
);

INSERT INTO vacant_jobs (
    job_id,
    title,
    description,
    posted_at,
    expires_at,
    is_active
)
VALUES (
    103,
    'Support Engineer',
    'PROVIDE TECHNICAL SUPPORT TO CUSTOMERS',
    SYSTIMESTAMP - INTERVAL '2' DAY,
    SYSTIMESTAMP - INTERVAL '1' HOUR,
    'Y'
);

INSERT INTO vacant_jobs (
    job_id,
    title,
    description,
    posted_at,
    expires_at,
    is_active
)
VALUES (
    104,
    'QA Tester',
    'TEST APPLICATION QUALITY',
    SYSTIMESTAMP - INTERVAL '3' DAY,
    SYSTIMESTAMP - INTERVAL '1' DAY,
    'N'
);

INSERT INTO job_applications (
    job_id,
    candidate_name,
    candidate_email
)
VALUES (
    101,
    'Ahmed Ali',
    'ahmed@example.com'
);

INSERT INTO job_applications (
    job_id,
    candidate_name,
    candidate_email
)
VALUES (
    101,
    'Mariam Said',
    'mariam@example.com'
);

INSERT INTO job_applications (
    job_id,
    candidate_name,
    candidate_email
)
VALUES (
    101,
    'Noor Salim',
    'noor@example.com'
);

INSERT INTO job_applications (
    job_id,
    candidate_name,
    candidate_email
)
VALUES (
    102,
    'Ali Hassan',
    'ali@example.com'
);

COMMIT;