CREATE TABLE vacant_jobs (
                        job_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        title VARCHAR2(200) NOT NULL,
                        description VARCHAR2(2000) NOT NULL,
                        expires_at TIMESTAMP NOT NULL,
                        active_flag CHAR(1) DEFAULT 'Y' NOT NULL,
                        created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

                        CONSTRAINT chk_job_active CHECK (active_flag IN ('Y', 'N'))
);

CREATE TABLE job_applications (
                            application_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            job_id NUMBER NOT NULL,
                            candidate_name VARCHAR2(200) NOT NULL,
                            candidate_email VARCHAR2(300),
                            applied_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

                            CONSTRAINT fk_application_job FOREIGN KEY (job_id) REFERENCES vacant_jobs(job_id)
);

CREATE TABLE jobs_posting_archive (
                                job_id NUMBER PRIMARY KEY,
                                title VARCHAR2(200) NOT NULL,
                                description VARCHAR2(2000) NOT NULL,
                                expires_at TIMESTAMP NOT NULL,
                                created_at TIMESTAMP NOT NULL
);

CREATE TABLE notifications (
                         notification_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         subject VARCHAR2(200) NOT NULL,
                         body VARCHAR2(4000) NOT NULL,
                         created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                         sent_flag CHAR(1) DEFAULT 'N' NOT NULL,

                         CONSTRAINT chk_notification_sent CHECK (sent_flag IN ('Y', 'N'))
);