-- Tables (ERD)

CREATE TABLE vacant_jobs (
    job_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR2(200)  NOT NULL,
    description  CLOB           NOT NULL,
    posted_at    TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    expires_at   TIMESTAMP      NOT NULL,
    active_flag  CHAR(1)        DEFAULT 'Y' NOT NULL,
    CONSTRAINT chk_vacant_active CHECK (active_flag IN ('Y', 'N'))
);

CREATE TABLE jobs_posting_archive (
    archive_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id       NUMBER         NOT NULL,
    title        VARCHAR2(200)  NOT NULL,
    description  CLOB           NOT NULL,
    posted_at    TIMESTAMP      NOT NULL,
    expires_at   TIMESTAMP      NOT NULL,
    archived_at  TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE job_applications (
    application_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id           NUMBER         NOT NULL,
    applicant_name   VARCHAR2(150)  NOT NULL,
    applicant_email  VARCHAR2(150)  NOT NULL,
    applied_at       TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    status           VARCHAR2(20)   DEFAULT 'NEW' NOT NULL,
    CONSTRAINT fk_app_job FOREIGN KEY (job_id)
        REFERENCES vacant_jobs (job_id),
    CONSTRAINT chk_app_status CHECK (status IN ('NEW', 'REVIEWED', 'SHORTLISTED', 'REJECTED'))
);

CREATE TABLE notifications (
    notification_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject         VARCHAR2(500)  NOT NULL,
    body            CLOB           NOT NULL,
    created_at      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    status          VARCHAR2(20)   DEFAULT 'PENDING' NOT NULL,
    sent_at         TIMESTAMP      NULL,
    source_type     VARCHAR2(30)   NOT NULL,
    source_id       NUMBER         NULL,
    CONSTRAINT chk_notif_status CHECK (status IN ('PENDING', 'SENT', 'FAILED')),
    CONSTRAINT chk_notif_source CHECK (source_type IN ('JOB_POSTED', 'JOB_EXPIRED', 'DAILY_DIGEST'))
);

CREATE INDEX idx_app_job ON job_applications (job_id);
CREATE INDEX idx_notif_status ON notifications (status);
CREATE INDEX idx_vacant_active ON vacant_jobs (active_flag, expires_at);
