-- Procedures

CREATE OR REPLACE PROCEDURE register_notification (
    p_subject     IN VARCHAR2,
    p_body        IN CLOB,
    p_source_type IN VARCHAR2,
    p_source_id   IN NUMBER DEFAULT NULL
)
IS
BEGIN
    INSERT INTO notifications (subject, body, status, source_type, source_id)
    VALUES (p_subject, p_body, 'PENDING', p_source_type, p_source_id);
END register_notification;
/

CREATE OR REPLACE PROCEDURE expire_vacancies
IS
BEGIN
    UPDATE vacant_jobs
       SET active_flag = 'N'
     WHERE active_flag = 'Y'
       AND expires_at <= SYSTIMESTAMP;
END expire_vacancies;
/

CREATE OR REPLACE PROCEDURE archive_inactive_jobs
IS
BEGIN
    BEGIN
        EXECUTE IMMEDIATE '
            CREATE TABLE jobs_posting_archive (
                archive_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                job_id       NUMBER         NOT NULL,
                title        VARCHAR2(200)  NOT NULL,
                description  CLOB           NOT NULL,
                posted_at    TIMESTAMP      NOT NULL,
                expires_at   TIMESTAMP      NOT NULL,
                archived_at  TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL
            )';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -955 THEN
                RAISE;
            END IF;
    END;

    INSERT INTO jobs_posting_archive (job_id, title, description, posted_at, expires_at)
    SELECT v.job_id, v.title, v.description, v.posted_at, v.expires_at
      FROM vacant_jobs v
     WHERE v.active_flag = 'N'
       AND NOT EXISTS (
             SELECT 1 FROM jobs_posting_archive a WHERE a.job_id = v.job_id
           );
END archive_inactive_jobs;
/

CREATE OR REPLACE PROCEDURE purge_inactive_jobs
IS
BEGIN
    DELETE FROM job_applications a
     WHERE a.job_id IN (
           SELECT v.job_id
             FROM vacant_jobs v
            WHERE v.active_flag = 'N'
              AND EXISTS (
                    SELECT 1 FROM jobs_posting_archive ar WHERE ar.job_id = v.job_id
                  )
           );

    DELETE FROM vacant_jobs v
     WHERE v.active_flag = 'N'
       AND EXISTS (
             SELECT 1 FROM jobs_posting_archive a WHERE a.job_id = v.job_id
           );
END purge_inactive_jobs;
/

CREATE OR REPLACE PROCEDURE archive_then_purge
IS
BEGIN
    archive_inactive_jobs;
    purge_inactive_jobs;
END archive_then_purge;
/

CREATE OR REPLACE PROCEDURE sweep_descriptions
IS
BEGIN
    FOR r IN (
        SELECT job_id, description
          FROM vacant_jobs
         WHERE active_flag = 'Y'
    ) LOOP
        UPDATE vacant_jobs
           SET description = my_lower(DBMS_LOB.SUBSTR(r.description, 4000, 1))
         WHERE job_id = r.job_id;
    END LOOP;
END sweep_descriptions;
/

CREATE OR REPLACE PROCEDURE make_application_digest
IS
    v_body CLOB := EMPTY_CLOB();
    v_cnt  NUMBER := 0;
    v_line VARCHAR2(4000);
BEGIN
    FOR r IN (
        SELECT v.job_id,
               DBMS_LOB.SUBSTR(v.description, 80, 1) AS desc_part,
               (SELECT COUNT(*)
                  FROM job_applications a
                 WHERE a.job_id = v.job_id) AS app_count
          FROM vacant_jobs v
         WHERE v.active_flag = 'Y'
         ORDER BY v.job_id
    ) LOOP
        v_cnt := v_cnt + 1;
        v_line := 'job ' || r.job_id
               || ' | ' || r.desc_part
               || ' | apps=' || r.app_count
               || CHR(10);
        v_body := v_body || v_line;
    END LOOP;

    IF v_cnt > 0 THEN
        register_notification(
            'daily application digest',
            v_body,
            'DAILY_DIGEST',
            NULL
        );
    END IF;
END make_application_digest;
/

CREATE OR REPLACE PROCEDURE get_pending_notifications (
    p_result OUT SYS_REFCURSOR
)
IS
BEGIN
    OPEN p_result FOR
        SELECT notification_id, subject, body, status, created_at,
               sent_at, source_type, source_id
          FROM notifications
         WHERE status = 'PENDING'
         ORDER BY notification_id;
END get_pending_notifications;
/

CREATE OR REPLACE PROCEDURE mark_notification_sent (
    p_id IN NUMBER
)
IS
BEGIN
    UPDATE notifications
       SET status  = 'SENT',
           sent_at = SYSTIMESTAMP
     WHERE notification_id = p_id
       AND status = 'PENDING';
END mark_notification_sent;
/
