-- 1. TABLES

CREATE TABLE vacant_jobs (
                             job_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             job_title       VARCHAR2(150) NOT NULL,
                             description     VARCHAR2(1000) NOT NULL,
                             expires_at      TIMESTAMP NOT NULL,
                             is_active       CHAR(1) DEFAULT 'Y' NOT NULL
                                 CONSTRAINT ck_vacant_jobs_active
                                     CHECK (is_active IN ('Y', 'N')),
                             created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE jobs_posting_archive (
                                      job_id          NUMBER PRIMARY KEY,
                                      job_title       VARCHAR2(150) NOT NULL,
                                      description     VARCHAR2(1000) NOT NULL,
                                      expires_at      TIMESTAMP NOT NULL,
                                      created_at      TIMESTAMP NOT NULL,
                                      archived_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE notifications (
                               notification_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               subject         VARCHAR2(200) NOT NULL,
                               body            VARCHAR2(2000) NOT NULL,
                               status          VARCHAR2(20) DEFAULT 'PENDING' NOT NULL
                    CONSTRAINT ck_notification_status
                    CHECK (status IN ('PENDING', 'SENT')),
                               created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                               sent_at         TIMESTAMP
);

CREATE TABLE job_applications (
                                  application_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  job_id          NUMBER NOT NULL,
                                  applicant_name  VARCHAR2(150) NOT NULL,
                                  applicant_email VARCHAR2(200) NOT NULL,
                                  applied_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                                  CONSTRAINT fk_application_job
                                      FOREIGN KEY (job_id)
                                          REFERENCES vacant_jobs(job_id)
                                          ON DELETE CASCADE
);

-- 2. SEED DATA

INSERT INTO vacant_jobs (job_title, description, expires_at)
VALUES ('Java Developer',
        'Java developer needed for backend team',
        SYSTIMESTAMP + INTERVAL '1' DAY);

INSERT INTO vacant_jobs (job_title, description, expires_at)
VALUES ('Database Administrator',
        'Experienced DBA required',
        SYSTIMESTAMP + INTERVAL '2' MINUTE);

INSERT INTO vacant_jobs (job_title, description, expires_at)
VALUES ('Network Engineer',
        'WE NEED A NETWORK ENGINEER WITH CISCO EXPERIENCE',
        SYSTIMESTAMP + INTERVAL '1' DAY);

COMMIT;

INSERT INTO job_applications (job_id, applicant_name, applicant_email)
VALUES (1, 'Ahmed Al-Rawahi', 'ahmed@example.com');

INSERT INTO job_applications (job_id, applicant_name, applicant_email)
VALUES (1, 'Sara Al-Rayami', 'sara@example.com');

INSERT INTO job_applications (job_id, applicant_name, applicant_email)
VALUES (1, 'Omar Al-Hosni', 'omar@example.com');

INSERT INTO job_applications (job_id, applicant_name, applicant_email)
VALUES (3, 'Maha Al-Badi', 'maha@example.com');

COMMIT;

-- 3. FUNCTION

CREATE OR REPLACE FUNCTION custom_lower
(
    p_text IN VARCHAR2
)
RETURN VARCHAR2
AS
    v_result VARCHAR2(4000) := '';
    v_char   CHAR(1);
BEGIN
FOR i IN 1 .. LENGTH(p_text)
    LOOP
        v_char := SUBSTR(p_text, i, 1);
        IF ASCII(v_char) BETWEEN 65 AND 90 THEN
            v_result := v_result || CHR(ASCII(v_char) + 32);
ELSE
            v_result := v_result || v_char;
END IF;
END LOOP;
RETURN v_result;
END custom_lower;
/

-- 4. PROCEDURES

CREATE OR REPLACE PROCEDURE register_notification
(
    p_subject IN VARCHAR2,
    p_body    IN VARCHAR2
)
AS
BEGIN
INSERT INTO notifications (subject, body)
VALUES (p_subject, p_body);
END register_notification;
/

CREATE OR REPLACE PROCEDURE process_job_description
(
    p_description IN  VARCHAR2,
    p_result      OUT VARCHAR2
)
AS
BEGIN
    p_result := custom_lower(p_description);
END process_job_description;
/

CREATE OR REPLACE PROCEDURE expire_jobs
AS
BEGIN
UPDATE vacant_jobs
SET is_active = 'N'
WHERE expires_at <= SYSTIMESTAMP
  AND is_active = 'Y';
COMMIT;
END expire_jobs;
/

-- Step 09 - Purge only safely archived inactive jobs.

CREATE OR REPLACE PROCEDURE purge_inactive_jobs
AS
BEGIN
DELETE FROM vacant_jobs v
WHERE v.is_active = 'N'
  AND EXISTS (
    SELECT 1
    FROM jobs_posting_archive a
    WHERE a.job_id = v.job_id
);
END purge_inactive_jobs;
/

-- Step 08 - Archive first, then call Step 09 purge.
CREATE OR REPLACE PROCEDURE archive_inactive_jobs
AS
BEGIN
INSERT INTO jobs_posting_archive
(job_id, job_title, description, expires_at, created_at)
SELECT
    job_id,
    job_title,
    description,
    expires_at,
    created_at
FROM vacant_jobs v
WHERE is_active = 'N'
  AND NOT EXISTS (
    SELECT 1
    FROM jobs_posting_archive a
    WHERE a.job_id = v.job_id
);

purge_inactive_jobs;
COMMIT;
END archive_inactive_jobs;
/

-- Step 10 - Implicit cursor sweep.
CREATE OR REPLACE PROCEDURE sweep_job_descriptions
AS
    v_cleaned_description VARCHAR2(4000);
BEGIN
FOR job_rec IN (
        SELECT job_id, description
        FROM vacant_jobs
        WHERE is_active = 'Y'
    )
    LOOP
        process_job_description(
            job_rec.description,
            v_cleaned_description
        );

UPDATE vacant_jobs
SET description = v_cleaned_description
WHERE job_id = job_rec.job_id;
END LOOP;
COMMIT;
END sweep_job_descriptions;
/

-- Step 12 - One daily digest using an implicit cursor.
CREATE OR REPLACE PROCEDURE create_application_digest
AS
    v_body VARCHAR2(4000) := '';
BEGIN
FOR job_rec IN (
        SELECT
            v.job_id,
            v.description,
            COUNT(a.application_id) AS application_count
        FROM vacant_jobs v
        LEFT JOIN job_applications a
            ON a.job_id = v.job_id
        GROUP BY v.job_id, v.description
        ORDER BY v.job_id
    )
    LOOP
        v_body := v_body
                  || 'Job ID: ' || job_rec.job_id
                  || ' | Description: ' || job_rec.description
                  || ' | Applications: ' || job_rec.application_count
                  || CHR(10);
END LOOP;

    register_notification('Daily Application Digest', v_body);
COMMIT;
END create_application_digest;
/

-- Step 13 - Explicit cursor handed to Spring Boot.
CREATE OR REPLACE PROCEDURE get_pending_notifications
(
    p_cursor OUT SYS_REFCURSOR
)
AS
BEGIN
OPEN p_cursor FOR
SELECT
    notification_id,
    subject,
    body,
    status,
    created_at
FROM notifications
WHERE status = 'PENDING'
ORDER BY notification_id;
END get_pending_notifications;
/


-- 5. TRIGGERS


CREATE OR REPLACE TRIGGER trg_vacancy_insert_notification
AFTER INSERT ON vacant_jobs
FOR EACH ROW
BEGIN
    register_notification(
        'New Vacancy Posted',
        'Job ID ' || :NEW.job_id || ' - ' || :NEW.job_title || ' has been posted.'
    );
END;
/

CREATE OR REPLACE TRIGGER trg_vacancy_description_update
BEFORE UPDATE OF description ON vacant_jobs
    FOR EACH ROW
DECLARE
v_cleaned_description VARCHAR2(4000);
BEGIN
    process_job_description(
        :NEW.description,
        v_cleaned_description
    );
    :NEW.description := v_cleaned_description;
END;
/

-- 6. SCHEDULED JOBS

BEGIN
    DBMS_SCHEDULER.CREATE_JOB(
        job_name        => 'JOB_EXPIRE_VACANCIES',
        job_type        => 'STORED_PROCEDURE',
        job_action      => 'EXPIRE_JOBS',
        start_date      => SYSTIMESTAMP,
        repeat_interval => 'FREQ=MINUTELY;INTERVAL=1',
        enabled         => TRUE
    );
END;
/

BEGIN
    DBMS_SCHEDULER.CREATE_JOB(
        job_name        => 'JOB_ARCHIVE_VACANCIES',
        job_type        => 'STORED_PROCEDURE',
        job_action      => 'ARCHIVE_INACTIVE_JOBS',
        start_date      => SYSTIMESTAMP,
        repeat_interval => 'FREQ=MINUTELY;INTERVAL=1',
        enabled         => TRUE
    );
END;
/

BEGIN
    DBMS_SCHEDULER.CREATE_JOB(
        job_name        => 'JOB_SWEEP_DESCRIPTIONS',
        job_type        => 'STORED_PROCEDURE',
        job_action      => 'SWEEP_JOB_DESCRIPTIONS',
        start_date      => SYSTIMESTAMP,
        repeat_interval => 'FREQ=MINUTELY;INTERVAL=1',
        enabled         => TRUE
    );
END;
/

BEGIN
    DBMS_SCHEDULER.CREATE_JOB(
        job_name        => 'JOB_DAILY_APPLICATION_DIGEST',
        job_type        => 'STORED_PROCEDURE',
        job_action      => 'CREATE_APPLICATION_DIGEST',
        start_date      => SYSTIMESTAMP,
        repeat_interval => 'FREQ=DAILY;INTERVAL=1',
        enabled         => TRUE
    );
END;
/


-- 7. VERIFICATION QUERIES

SELECT * FROM vacant_jobs;
SELECT * FROM job_applications;
SELECT * FROM notifications;
SELECT * FROM jobs_posting_archive;

SELECT
    job_name,
    state,
    repeat_interval,
    last_start_date,
    next_run_date
FROM user_scheduler_jobs
WHERE job_name IN (
                   'JOB_EXPIRE_VACANCIES',
                   'JOB_ARCHIVE_VACANCIES',
                   'JOB_SWEEP_DESCRIPTIONS',
                   'JOB_DAILY_APPLICATION_DIGEST'
    )
ORDER BY job_name;
