-- Create VacancyLoop tables

CREATE TABLE vacant_jobs (
    job_id       NUMBER
                     GENERATED BY DEFAULT AS IDENTITY,
    job_title    VARCHAR2(150) NOT NULL,
    description  VARCHAR2(1000) NOT NULL,
    posted_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    expires_at   TIMESTAMP NOT NULL,
    is_active    CHAR(1) DEFAULT 'Y' NOT NULL,

    CONSTRAINT pk_vacant_jobs
        PRIMARY KEY (job_id),

    CONSTRAINT chk_vacant_jobs_active
        CHECK (is_active IN ('Y', 'N'))
);

CREATE TABLE notifications (
    notification_id  NUMBER
                         GENERATED BY DEFAULT AS IDENTITY,
    job_id            NUMBER,
    subject           VARCHAR2(200) NOT NULL,
    body              VARCHAR2(4000) NOT NULL,
    created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    sent_at           TIMESTAMP,

    CONSTRAINT pk_notifications
        PRIMARY KEY (notification_id),

    CONSTRAINT fk_notifications_job
        FOREIGN KEY (job_id)
        REFERENCES vacant_jobs (job_id)
        ON DELETE SET NULL
);

CREATE TABLE job_applications (
    application_id  NUMBER
                        GENERATED BY DEFAULT AS IDENTITY,
    job_id           NUMBER NOT NULL,
    applicant_name   VARCHAR2(150) NOT NULL,
    applicant_email  VARCHAR2(255) NOT NULL,
    applied_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_job_applications
        PRIMARY KEY (application_id),

    CONSTRAINT fk_applications_job
        FOREIGN KEY (job_id)
        REFERENCES vacant_jobs (job_id)
        ON DELETE CASCADE
);

CREATE TABLE jobs_posting_archive (
    job_id       NUMBER NOT NULL,
    job_title    VARCHAR2(100) NOT NULL,
    description  VARCHAR2(1000) NOT NULL,
    posted_at    TIMESTAMP(6) NOT NULL,
    expires_at   TIMESTAMP(6) NOT NULL,

    CONSTRAINT pk_jobs_posting_archive
        PRIMARY KEY (job_id)
);
