-- ========================= 01_create_tables.sql =========================

-- Create VACANT_JOBS table
CREATE TABLE vacant_jobs (
    job_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           VARCHAR2(200) NOT NULL,
    description     VARCHAR2(1000) NOT NULL,
    expires_at      TIMESTAMP NOT NULL,
    active          CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CHECK (active IN ('Y', 'N'))
);

-- Create JOB_APPLICATIONS table
CREATE TABLE job_applications (
    application_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    applicant_name  VARCHAR2(200) NOT NULL,
    applicant_email VARCHAR2(200) NOT NULL,
    applied_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    job_id NUMBER NOT NULL REFERENCES vacant_jobs(job_id) ON DELETE CASCADE
);

-- Create NOTIFICATIONS table
CREATE TABLE notifications (
    notification_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject         VARCHAR2(500) NOT NULL,
    body            VARCHAR2(2000) NOT NULL,
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    status          VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    sent_at         TIMESTAMP,
    related_job_id NUMBER REFERENCES vacant_jobs(job_id) ON DELETE SET NULL,
    CHECK (status IN ('PENDING', 'SENT', 'FAILED'))
);

-- Create JOBS_POSTING_ARCHIVE table
CREATE TABLE jobs_posting_archive (
    job_id          NUMBER PRIMARY KEY,
    title           VARCHAR2(200) NOT NULL,
    description     VARCHAR2(1000) NOT NULL,
    expires_at      TIMESTAMP NOT NULL,
    created_at      TIMESTAMP NOT NULL,
    archived_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

--------------------------------------------------------------------------------
-- Display all tables created by the current user
SELECT table_name
FROM user_tables
ORDER BY table_name;